apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epiphany-web-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: epiphany-web
    spec:
      containers:
      - name: epiphany-web
        image: your-docker-repository.azurecr.io/epiphany-web
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector:
         beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: epiphany-web-svc
  labels:
    version: 1.0.0
spec:
  selector:
    app: epiphany-web
  ports:
  - port: 80
    nodePort: 30001
  type: NodePort
