
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-kafka-connector
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: iothub-kafka-connector
    spec:
      containers:
      - name: iothub-kafka-connector
        image: toszo/iothub-kafka-connector:0.1.2
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: KAFKA_ENDPOINT
          value: "10.0.4.6:9092" # Put here IP private IP/hostname and port of your Kafka instance
        - name: KAFKA_SESSION_TIMEOUT_MS
          value: "10000"
        - name: DATA_TOPIC_NAME
          value: "iot-data"
        - name: CONFIG_TOPIC_NAME
          value: "iot-config"
        - name: EVENT_TOPIC_NAME
          value: "iot-event"
        - name: ALARM_TOPIC_NAME
          value: "iot-alarm"
        - name: EVENTHUB_CONNECTIONSTRING
          value: ""
        - name: EVENTHUB_NAME
          value: ""
        - name: STORAGE_CONTAINER_NAME
          value: ""
        - name: STORAGE_ACCOUNT_NAME
          value: ""
        - name: STORAGE_ACCOUNT_KEY
          value: ""
        # ---
        # Kubernetes specific - no need to change
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        # ---
