apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-web-producer
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kafka-web-producer
    spec:
      containers:
      - name: kafka-web-producer
        image:  your-docker-repository.azurecr.io/samples/kafka-webproducer:v6
        imagePullPolicy: Always
        env:
          - name: KAFKA_SESSION_TIMEOUT_MS
            valueFrom:
              configMapKeyRef:
                name: kafka
                key: KAFKA_SESSION_TIMEOUT_MS
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: kafka
                key: KAFKA_BOOTSTRAP_SERVERS
          - name: KAFKA_AUTO_COMMIT_INVETRVAL_MS
            valueFrom:
              configMapKeyRef:
                name: kafka
                key: KAFKA_AUTO_COMMIT_INVETRVAL_MS
          - name: KAFKA_GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: kafka
                key: KAFKA_GROUP_ID
          - name: KAFKA_AUTO_OFFSET_RESET
            valueFrom:
              configMapKeyRef:
                name: kafka
                key: KAFKA_AUTO_OFFSET_RESET
         
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registrysecretname
