apiVersion: v1
kind: Pod
metadata:
  name: kafka-web-producer-pod
spec:
  containers:
    - name: kafka-web-producer
      image:  your-docker-repository.azurecr.io/examples/kafka-webpducer:v2
      imagePullPolicy: Always
      env:
        - name: KAFKA_SESSION_TIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_SESSION_TIMEOUT_MS
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_AUTO_COMMIT_INVETRVAL_MS
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_AUTO_COMMIT_INVETRVAL_MS
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_GROUP_ID
        - name: KAFKA_AUTO_OFFSET_RESET
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_AUTO_OFFSET_RESET
  restartPolicy: Always
  imagePullSecrets:
  - name: registrysecretname
