---
apiVersion: v1
kind: Service
metadata:
  name: kafka-web-producer
  labels:
    version: 1.0.0
spec:
  selector:
    app: kafka-web-producer
  ports:
  - port: 80
    nodePort: 30001
  type: NodePort
