---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epiphany-kafka-elk-connector
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: epiphany-kafka-elk-connector
    spec:
      containers:
      - name: epiphany-kafka-elk-connector
        image: toszo/kafka-elk-connector:0.1.9
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          value: "kafka_ip:9092"
        - name: TOPIC
          value: "your-data-topic"
        - name: GROUP_ID
          value: "your-consumer-group"
        - name: ELASTICSEARCH_URL
          value: "http://elastic_IP:9200"
        - name: INDEX_NAME
          value: "yourindexname"